### ISSUE TITLE
Allow demo server to be deployed to Heroku from the master branch

### ISSUE THREAD

**Issue by dnrce** [dnrce/tracks#35]
Steps to accomplish this:
- [ ] Move config into `ENV` (12 factor) #34 
- [ ] Enable Postgres TracksApp/tracks#1892
- [ ] Redirect to signup page with open signup #28 
- [ ] Add a database reset task for the demo environment
